#!/bin/bash

#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=Agent
#SBATCH --ntasks-per-node=8
#SBATCH --time=4:00:00

source /home/mjad1g20/.bashrc
#module load conda/py3-latest
source activate rrlib
#conda env list
python --version
which python
python ray_ddpg.py
